# All constants

# ACTION for authenticator
ACTION_LOGIN = 1
ACTION_SIGNUP = 2
ACTION_SENDMESSAGE = 3
ACTION_LOGIN_REQUIRED = 4

# ACTION for client helper
ACTION_SEARCH = 5
ACTION_ADDFRIEND = 6
ACTION_REMOVEFRIEND = 7
ACTION_RETRIEVEONLINE = 8
ACTION_GETFRIENDS = 9
ACTION_POSTBLOG = 10
ACTION_GETDETAIL = 11
ACTION_GETBLOG = 12
ACTION_GETAVATAR = 13
ACTION_SETAVATAR = 14
ACTION_EXIT = 15


SERVER_NAME='localhost'
SERVER_PORT='8888'
NUM_HOSTS = 10

EXISTED_USERNAME = 100

STATUS_OK = '200-OK'
STATUS_BAD = '400-BAD'
STATUS_NOTFOUND = '404-NOT FOUND'

STATUS_BADPASS = 'BAD PASSWORD'
STATUS_UNREGISTER = 'UNREGISTER USER'

RESOURCE_DIR = 'resource'
PROFILE_PATH = 'profile_pics'